### ISSUE TITLE
Installation Process

### ISSUE THREAD

**Issue by deandrehaijiel** [tsAppDevelopment/react-icon-cloud#3]
Hi Teague, DeAndre here. First and foremost, thank you for the effort in building this. It is exactly what I am looking for. However, I do apologise as I am just starting out learning React and I can't seem to get this to work. It shows 'NO TAGS' on my web application. Could we connect and please guide me though the process of getting this to work? Thank you for your kind attention, hope to hear from you soon.

**Comment by teaguestockwell** [comment]
Hi DeAndre,

I would be happy to help. Do you have a repro of this issue? A code sandbox may be helpful for this.

**Comment by deandrehaijiel** [comment]
Hi, this is the repo: https://github.com/deandrehaijiel/react-portfolio I am implementing this in src/components/Skills

**Comment by deandrehaijiel** [comment]
Do let me know if I am doing anything wrong

**Comment by deandrehaijiel** [comment]
Sorry for the delay but the sandbox link is here: https://codesandbox.io/s/keen-field-52wd6u I have since removed the code but am trying to implement it on the right side of the Skills Page

**Comment by deandrehaijiel** [comment]
Hi, I am trying to replicate your result here: https://codesandbox.io/s/react-icon-cloud-1xr9h?file=/dynamic-cloud.tsx. The code sandbox is https://codesandbox.io/s/stoic-moon-3rugwv , currently running with error. It is throwing me with "Module '"."' has no exported member 'cloudProps'. Did you mean to use 'import cloudProps from "."' instead?" over at dynamic-cloud.tsx in the skills folder

**Comment by teaguestockwell** [comment]
Great looking portfolio DeAndre. I hope this helps 😃 

## Issue
The main reason it was not working originally is because in the example [here](https://codesandbox.io/s/react-icon-cloud-1xr9h?file=/dynamic-cloud.tsx) the syntax is commonly called a named ESM import:
```js
import { cloudProps } from '.' 
```

It expects the file `index.js` to export `cloudProps` like this:
```js
export const cloudProps = {}
```
[This](https://webpack.js.org/guides/ecma-script-modules/) may also be a helpful doc to understand ESM import better.

## Fix
[here is a working fork of that codesandbox](https://codesandbox.io/s/deandre-tf4phn?file=/src/components/Skills/dynamic-cloud.js) where I
- renamed dynamic-cloud.tsx to dynamic-cloud.js
- removed typescript types from src/Skills/index.js
- removed the broken import and added: `const cloudProps = {}` to dynamic-cloud.js
- added: `import { DynamicCloud } from './dynamic-cloud'` to src/Skills/index.js and rendered it using the slugs

## TODO
Notice that only one icon is displayed:
![Screen Shot 2022-08-06 at 17 11 56](https://user-images.githubusercontent.com/71202372/183269722-dc4d5e03-8aa4-4f7e-adf7-89f1294275d3.png)

This is because the slugs are case sensitive. You can fix this by using the [example codesandbox](https://codesandbox.io/s/react-icon-cloud-1xr9h) to select your icons, then replace src/Skills/index.js `const slugs = [...]` with the array below the dropdown:
![Screen Shot 2022-08-06 at 16 55 53](https://user-images.githubusercontent.com/71202372/183269445-945e26e7-572f-462a-bd47-52abfdb3795b.png)

**Comment by deandrehaijiel** [comment]
this is amazing! thank you so much!!!

**Comment by deandrehaijiel** [comment]
Hi, everything is working fine now but i noticed that the Icon Cloud will reload after 1 second after appearing. Any ideas why is that so and how I could eliminate this? CodeSandbox: https://codesandbox.io/s/lingering-cloud-j8hogm

**Comment by deandrehaijiel** [comment]
Hi, everything is working fine now but i noticed that the Icon Cloud will reload after 1 second after appearing. Any ideas why is that so and how I could eliminate this? CodeSandbox: https://codesandbox.io/s/lingering-cloud-j8hogm

**Comment by teaguestockwell** [comment]
If you are using the dynamic cloud, then its initial state is to render without icons while they are being fetched.

You may add a loading state (render a spinner instead of the cloud when icons.length === 0) or [use static simple icon imports](https://github.com/teaguestockwell/react-icon-cloud#static-icon-slugs)

**Comment by deandrehaijiel** [comment]
Got it! I decided to make a fade in animation to have a little bit of delay. however, would it be okay if you come up with a static code for what i have? 😅

**Comment by teaguestockwell** [comment]
If you would like to remove the loading state, please use the [example](https://github.com/teaguestockwell/react-icon-cloud#static-icon-slugs) for using the cloud with static imports.

**Comment by deandrehaijiel** [comment]
thank you!!!
