### ISSUE TITLE
Wrong imports ?

### ISSUE THREAD

**Issue by valentinllpz** [tsAppDevelopment/react-icon-cloud#4]
Hello,

I am very interested in using this package because it really looks awesome ! However I can't get it to work because imports seem broken.  I tried to downgrade Simple-Icons to the same version as  your code sandbox example but it still does not work, I get the following issue:
`TypeError: (0 , react_icon_cloud__WEBPACK_IMPORTED_MODULE_2__.renderSimpleIcon) is not a function`

My package.json setup : 
[...]
```
   "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-icon-cloud": "^4.1.4",
    "simple-icons": "^5.12.0"
```

**Comment by teaguestockwell** [comment]
Can you create a code sandbox to reproduce this? I made one [here](https://codesandbox.io/s/exciting-chebyshev-ucm4w5?file=/index.tsx) but cant repro the webpack issue

**Comment by valentinllpz** [comment]
Codesandbox : https://codesandbox.io/s/issue-react-icons-sphere-fyz8wo

The message is more explicit when trying to use it with NextJS + TS on my computer:
<img width="963" alt="image" src="https://user-images.githubusercontent.com/54294833/189606147-6a582ed8-c84b-48a0-93f6-010d98bf387d.png">

Also, if you try to edit your sandbox and update the simple-icons package to latest it won't work.

**Comment by teaguestockwell** [comment]
Looks like a typo or possible a hot reload error: This should be `renderSimpleIcon`, instead of `renderSimpleIconp`. Either way, looks like you got it [working on your portfolio](https://github.com/valentinllpz/portefolio_v2/blob/main/src/app/components/SkillCloud.tsx). Great looking site btw :) thanks for choosing to use the simple-icon-cloud to showcase some tools you've worked with :)
